CREATE TABLE `breeds` (
    `id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(100) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `breeds_name_key`(`name`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- シードデータ: 主要犬種
INSERT INTO `breeds` (`id`, `name`) VALUES
  (UUID(), '柴犬'),
  (UUID(), 'トイプードル'),
  (UUID(), 'ミニチュアプードル'),
  (UUID(), 'スタンダードプードル'),
  (UUID(), 'チワワ'),
  (UUID(), 'フレンチブルドッグ'),
  (UUID(), 'ミニチュアダックスフンド'),
  (UUID(), 'カニンヘンダックスフンド'),
  (UUID(), 'ポメラニアン'),
  (UUID(), 'ゴールデンレトリバー'),
  (UUID(), 'ラブラドールレトリバー'),
  (UUID(), 'マルチーズ'),
  (UUID(), 'ヨークシャーテリア'),
  (UUID(), 'ビーグル'),
  (UUID(), 'ウェルシュコーギー'),
  (UUID(), 'シェットランドシープドッグ'),
  (UUID(), 'ボーダーコリー'),
  (UUID(), '秋田犬'),
  (UUID(), '日本スピッツ'),
  (UUID(), 'サモエド'),
  (UUID(), 'シベリアンハスキー'),
  (UUID(), 'ジャックラッセルテリア'),
  (UUID(), 'パグ'),
  (UUID(), 'シーズー'),
  (UUID(), 'マルプー'),
  (UUID(), 'キャバリア'),
  (UUID(), 'ビションフリーゼ'),
  (UUID(), 'ミニチュアシュナウザー'),
  (UUID(), 'ウェストハイランドホワイトテリア'),
  (UUID(), 'スコティッシュテリア'),
  (UUID(), 'バセットハウンド'),
  (UUID(), 'ダルメシアン'),
  (UUID(), 'ジャーマンシェパード'),
  (UUID(), 'ドーベルマン'),
  (UUID(), 'ロットワイラー'),
  (UUID(), 'ボクサー'),
  (UUID(), 'グレートデン'),
  (UUID(), 'バーニーズマウンテンドッグ'),
  (UUID(), 'ハバニーズ'),
  (UUID(), 'パピヨン'),
  (UUID(), 'イタリアングレーハウンド'),
  (UUID(), 'ウィペット'),
  (UUID(), 'アフガンハウンド'),
  (UUID(), 'ブルドッグ'),
  (UUID(), 'ボストンテリア'),
  (UUID(), 'ミックス犬（雑種）');
